version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"

    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  celery:
    restart: always
    build: .
    command: celery -A kernel_calculation worker -l info
    volumes:
      - ./src:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web
volumes:
  pgdata: